#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

foamListTimes -rm -withZero

# Remove old log.* files 
rm -f log.* 
rm -f log
rm -rf processor* 
#rm -rf constant/polyMesh/
rm -f OAR.*
rm -f simulationProperties.py


#------------------------------------------------------------------------------


